//------- boolSlice.js -------->

//------- Import the createSlice function from Redux Toolkit -------->
import { createSlice } from "@reduxjs/toolkit";

//------- Initial state for the bool slice -------->
const initialState = {
  sidebarBool: true, //------- Boolean to control the visibility of the sidebar -------->
};

//------- Define the bool slice using createSlice -------->
const boolSlice = createSlice({
  name: "bool", //------- Name of the slice -------->
  initialState, //------- Initial state -------->
  reducers: {
    //------- Reducer to set the boolean value for sidebar visibility -------->
    setSidebarBool: (state, action) => {
      state.sidebarBool = action.payload;
    },
  },
});

//------- Export the actions generated by the boolSlice -------->
export const { setSidebarBool } = boolSlice.actions;

//------- Selector to retrieve sidebar visibility boolean from the state -------->
export const selectSidebarBool = (state) => state.bool.sidebarBool;

//------- Export the reducer generated by the boolSlice -------->
export default boolSlice.reducer;
