import React from "react";
import MobileScreenShareOutlinedIcon from "@mui/icons-material/MobileScreenShareOutlined";
import DevicesIcon from "@mui/icons-material/Devices";
import PeopleAltOutlinedIcon from "@mui/icons-material/PeopleAltOutlined";
import QueryBuilderOutlinedIcon from "@mui/icons-material/QueryBuilderOutlined";
import StarBorderOutlinedIcon from "@mui/icons-material/StarBorderOutlined";
import DeleteOutlineOutlinedIcon from "@mui/icons-material/DeleteOutlineOutlined";
import CloudQueueIcon from "@mui/icons-material/CloudQueue";
import SearchIcon from "@mui/icons-material/Search";
import HelpOutlineIcon from "@mui/icons-material/HelpOutline";
import SettingsOutlinedIcon from "@mui/icons-material/SettingsOutlined";
import AppsOutlinedIcon from "@mui/icons-material/AppsOutlined";
import FormatAlignCenterOutlinedIcon from "@mui/icons-material/FormatAlignCenterOutlined";
import ArrowDropDownIcon from "@mui/icons-material/ArrowDropDown";
import ListIcon from "@mui/icons-material/List";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";
import InsertDriveFileIcon from "@mui/icons-material/InsertDriveFile";
import ArrowDownwardIcon from "@mui/icons-material/ArrowDownward";
import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf';
import PermMediaOutlinedIcon from '@mui/icons-material/PermMediaOutlined';
import AudioFileOutlinedIcon from '@mui/icons-material/AudioFileOutlined';
import VideoLibraryOutlinedIcon from '@mui/icons-material/VideoLibraryOutlined';

export const MobileScreenShareIcon = () => <MobileScreenShareOutlinedIcon />;
export const DevicesIcons = () => <DevicesIcon />;
export const PeopleAltIcon = () => <PeopleAltOutlinedIcon />;
export const QueryBuilderIcon = () => <QueryBuilderOutlinedIcon />;
export const StarBorderIcon = () => <StarBorderOutlinedIcon />;
export const DeleteOutlineIcon = () => <DeleteOutlineOutlinedIcon />;
export const CloudQueueIcons = () => <CloudQueueIcon />;
export const SearchIcons = () => <SearchIcon />;
export const HelpIcon = () => <HelpOutlineIcon />;
export const SettingsIcon = () => <SettingsOutlinedIcon />;
export const AppsIcon = () => <AppsOutlinedIcon />;
export const FormatIcon = () => <FormatAlignCenterOutlinedIcon />;
export const ArrowDDownIcon = () => <ArrowDropDownIcon />;
export const ListsIcon = () => <ListIcon />;
export const InfoIcon = () => <InfoOutlinedIcon />;
export const FileIcon = () => <InsertDriveFileIcon />;
export const ArrowDownIcon = () => <ArrowDownwardIcon />;
export const PdfIcon = () => <PictureAsPdfIcon />;
export const PermMediaIcon = () => <PermMediaOutlinedIcon />;
export const AudioIcon = () => <AudioFileOutlinedIcon />;
export const VideoIcon = () => <VideoLibraryOutlinedIcon />;