import React from "react";
import MobileScreenShareOutlinedIcon from "@mui/icons-material/MobileScreenShareOutlined";
import DevicesIcon from "@mui/icons-material/Devices";
import PeopleAltOutlinedIcon from "@mui/icons-material/PeopleAltOutlined";
import QueryBuilderOutlinedIcon from "@mui/icons-material/QueryBuilderOutlined";
import StarBorderOutlinedIcon from "@mui/icons-material/StarBorderOutlined";
import DeleteOutlineOutlinedIcon from "@mui/icons-material/DeleteOutlineOutlined";
import CloudQueueIcon from "@mui/icons-material/CloudQueue";
import SearchIcon from "@mui/icons-material/Search";
import HelpOutlineIcon from "@mui/icons-material/HelpOutline";
import SettingsOutlinedIcon from "@mui/icons-material/SettingsOutlined";
import AppsOutlinedIcon from "@mui/icons-material/AppsOutlined";
import FormatAlignCenterOutlinedIcon from "@mui/icons-material/FormatAlignCenterOutlined";
import ArrowDropDownIcon from "@mui/icons-material/ArrowDropDown";
import ListIcon from "@mui/icons-material/List";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";
import DescriptionOutlinedIcon from '@mui/icons-material/DescriptionOutlined';
import ArrowDownwardIcon from "@mui/icons-material/ArrowDownward";
import PictureAsPdfIcon from '@mui/icons-material/PictureAsPdf';
import PermMediaOutlinedIcon from '@mui/icons-material/PermMediaOutlined';
import AudioFileOutlinedIcon from '@mui/icons-material/AudioFileOutlined';
import VideoLibraryOutlinedIcon from '@mui/icons-material/VideoLibraryOutlined';
import MoreHorizIcon from '@mui/icons-material/MoreHoriz';
import MenuRoundedIcon from '@mui/icons-material/MenuRounded';
import StarOutlinedIcon from '@mui/icons-material/StarOutlined';
import FileDownloadOutlinedIcon from '@mui/icons-material/FileDownloadOutlined';
import ReplyOutlinedIcon from '@mui/icons-material/ReplyOutlined';
import DeleteRoundedIcon from '@mui/icons-material/DeleteRounded';
import ContentCopyRoundedIcon from '@mui/icons-material/ContentCopyRounded';
import CloseRoundedIcon from '@mui/icons-material/CloseRounded';
import GitHubIcon from '@mui/icons-material/GitHub';
import FacebookOutlinedIcon from '@mui/icons-material/FacebookOutlined';
import LinkedInIcon from '@mui/icons-material/LinkedIn';
import InstagramIcon from '@mui/icons-material/Instagram';
import AppsRoundedIcon from '@mui/icons-material/AppsRounded';
import DisabledByDefaultOutlinedIcon from '@mui/icons-material/DisabledByDefaultOutlined';
import UploadFileRoundedIcon from '@mui/icons-material/UploadFileRounded';

export const MobileScreenShareIcon = () => <MobileScreenShareOutlinedIcon />;
export const DevicesIcons = () => <DevicesIcon />;
export const PeopleAltIcon = () => <PeopleAltOutlinedIcon />;
export const QueryBuilderIcon = () => <QueryBuilderOutlinedIcon />;
export const StarBorderIcon = () => <StarBorderOutlinedIcon />;
export const DeleteOutlineIcon = () => <DeleteOutlineOutlinedIcon />;
export const CloudQueueIcons = () => <CloudQueueIcon />;
export const SearchIcons = () => <SearchIcon />;
export const HelpIcon = () => <HelpOutlineIcon />;
export const SettingsIcon = () => <SettingsOutlinedIcon />;
export const AppsIcon = () => <AppsOutlinedIcon />;
export const FormatIcon = () => <FormatAlignCenterOutlinedIcon />;
export const ArrowDDownIcon = () => <ArrowDropDownIcon />;
export const ListsIcon = () => <ListIcon />;
export const InfoIcon = () => <InfoOutlinedIcon />;
export const FileIcon = () => <DescriptionOutlinedIcon />;
export const ArrowDownIcon = () => <ArrowDownwardIcon />;
export const PdfIcon = () => <PictureAsPdfIcon />;
export const PermMediaIcon = () => <PermMediaOutlinedIcon />;
export const AudioIcon = () => <AudioFileOutlinedIcon />;
export const VideoIcon = () => <VideoLibraryOutlinedIcon />;
export const MoreOptionsIcon = () => <MoreHorizIcon />;
export const MenuIcon = () => <MenuRoundedIcon />;
export const StarFilledIcon = () => <StarOutlinedIcon />;
export const DownloadIcon = () => <FileDownloadOutlinedIcon />;
export const ShareIcon = () => <ReplyOutlinedIcon />;
export const DeleteIcon = () => <DeleteRoundedIcon />;
export const CopyIcon = () => <ContentCopyRoundedIcon />;
export const CloseIcon = () => <CloseRoundedIcon />;
export const GitIcon = () => <GitHubIcon />;
export const FacebookIcon = () => <FacebookOutlinedIcon />;
export const LinkedIcon = () => <LinkedInIcon />;
export const InstaIcon = () => <InstagramIcon />;
export const GridIcon = () => <AppsRoundedIcon />;
export const CloseButton = () => <DisabledByDefaultOutlinedIcon />;
export const UploadFileIcon = () => <UploadFileRoundedIcon />;